# Generated by Django 2.2.9 on 2020-02-01 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
        ('architecture', '0002_auto_20200201_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('incharge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrations.Person')),
                ('rooms', models.ManyToManyField(blank=True, to='architecture.Room')),
            ],
        ),
    ]
