# Generated by Django 2.2.9 on 2020-02-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20200201_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
