# Generated by Django 2.2.9 on 2020-02-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('office', 'Office'), ('faculty_cabin', 'Faculty Cabin'), ('classroom', 'Class Room'), ('lab', 'Lab'), ('workspace', 'Workspace'), ('other', 'Other')], max_length=100),
        ),
    ]
