# Generated by Django 2.2.9 on 2020-02-01 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20200201_0526'),
        ('architecture', '0002_auto_20200201_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='occupants',
        ),
        migrations.AddField(
            model_name='room',
            name='occupant',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='registrations.Person'),
            preserve_default=False,
        ),
    ]
