# Generated by Django 2.2.9 on 2020-02-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0003_auto_20200201_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fig_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='fig_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
