# Generated by Django 2.2.9 on 2020-02-01 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0005_auto_20200201_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('floor', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('fig_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='door',
            name='fig_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='fig_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='number',
        ),
        migrations.AddField(
            model_name='door',
            name='ga',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='architecture.GenericAsset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='ga',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='architecture.GenericAsset'),
            preserve_default=False,
        ),
    ]
