# Generated by Django 2.2.9 on 2020-02-01 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0006_auto_20200201_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='occupant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registrations.Person'),
        ),
    ]
